---
# Playbook zur Konfiguration aller Servern von domaene-01
# Aufruf einer einzelnen Rolle möglich. Beispiel nur fastd: "ansible-playbook bgp.yml --tags="common"

- hosts: bgp
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: iptables_netbone, tags: "iptables_netbone"}
    - { role: rclocal_netbone, tags: "rclocal_netbone"}
    - { role: interfaces_netbone_ffrl, tags: "interfaces_netbone_ffrl"}
    - { role: interfaces_netbone_interconnect, tags: "interfaces_netbone_interconnect"}
    - { role: interfaces_netbone_direct_gw, tags: "interfaces_netbone_direct_gw"}
    - { role: bird_netbone, tags: "bird_netbone"}
    - { role: bird_install, tags: "bird_install"}
