---
# Playbook zur Konfiguration aller Servern von domaene-01
# Aufruf einer einzelnen Rolle möglich. Beispiel nur fastd: "ansible-playbook bgp.yml --tags="common"

- hosts: bgp
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: iptables_netbone, tags: "iptables_netbone"}
    - { role: rclocal_netbone, tags: "rclocal_netbone"}
    - { role: interfaces_netbone_ffrl, tags: "interfaces_netbone_ffrl"}
    - { role: interfaces_netbone_internal, tags: "interfaces_netbone_internal"}
    - { role: interfaces_direct, tags: "interfaces_direct"}
    - { role: bird_install, tags: "bird_install"}
    - { role: bird_netbone, tags: "bird_netbone"}
    - { role: icvpn_netbone, tags: "icvpn_netbone"}
    - { role: stats_netbone, tags: "stats_netbone"}
