---
- name: Schlüssel für universe-factory Repo hinzufügen
  apt_key: id=16EF3F64CB201D9C keyserver=pool.sks-keyservers.net state=present

- name: universe-factory Repo hinzufügen
  apt_repository:
    repo: "deb https://repo.universe-factory.net/debian/ sid main"
    state: present

- name: draic Repo hinzufügen
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb [arch=amd64] https://debian.draic.info/ wheezy main
    - deb-src https://debian.draic.info/ wheezy main
