---

- name: configure rc.local
  template: src=rc.local.j2 dest=/etc/rc.local owner=root group=root mode=0755
  notify:
    - restart rc.local

#Beachten dass alte Einträge nicht angefasst werden
- name: rc.local aktivieren und starten
  service: name=rc.local state=started enabled=yes
  #todo: Wegen Jessie und Wheezy VMs benötigt
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

- name: Fire all previous handlers
  meta: flush_handlers
