---
# Tasks for network interfaces

# adding ffrl natv4 address to loopback adapter
#- name: Create interfaces - add ffrl to loopback
#  lineinfile:
     #dest='/etc/network/interfaces'
     #regexp='^[ \t]+up ip address add.*$'
     #insertafter='^iface lo inet loopback.*$'
     #line='        up ip address add {{server_ipv4_nat}} dev lo'

# - name: Create interfaces - add ffrl-rule to loopback
#   lineinfile:
#      dest='/etc/network/interfaces'
#      regexp='^[ \t]+up ip rule add from.*$'
#      insertafter='^[ \t]+up ip address add.*$'
#      line='        up ip rule add from {{server_ipv4_nat}} table ffnet'

# - name: Create interfaces - add suppress_prefixlength-rule
#   lineinfile:
#      dest='/etc/network/interfaces'
#      insertafter='^[ \t]+up ip rule add from.*$'
#      line='        up ip rule add iif lo table ffnet suppress_prefixlength 0'
#
# - name: Create interfaces - add v6 suppress_prefixlength-rule
#   lineinfile:
#      dest='/etc/network/interfaces'
#      insertafter='^[ \t]+up ip rule add iif lo table ffnet suppress_prefixlength 0.*$'
#      line='        up ip -6 rule add iif lo table ffnet suppress_prefixlength 0'


# creating gre tunnels to FFWP Backbone
- name: Create interfaces - internal_gre
  template: src="internal_gre.j2" dest="/etc/network/interfaces.d/39_internal_gre.cfg"
  notify:
    - restart networking

#append line in interfaces file for reading additional config files
- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*"
  notify:
    - restart networking
