---

- name: Routingtabelle 42 auch freifunk nennen
  lineinfile: dest="/etc/iproute2/rt_tables" line="42   freifunk"

- name: Routingtabelle 43 auch interior nennen
  lineinfile: dest="/etc/iproute2/rt_tables" line="43   interior"

#todo: check bird.conf before restart bird!!!
- name: configure bird.conf
  template: src=bird.conf.j2 dest=/etc/bird/bird.conf
  notify:
    - restart bird

- name: configure bird6.conf
  template: src=bird6.conf.j2 dest=/etc/bird/bird6.conf
  notify:
   - restart bird6

- name: bird aktivieren und starten
  service: name=bird state=started enabled=yes

- name: bird aktivieren (Workaround weil enable=yes nicht tut)
  command: systemctl enable bird
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'


- name: bird6 aktivieren und starten
  service: name=bird6 state=started enabled=yes

- name: bird6 aktivieren (Workaround weil enable=yes nicht tut)
  command: systemctl enable bird6
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'
