---
# Allgemeine Konfigurationen für alle Server

- name: add default repo
  #Freifunk- und Rollen-Repos erst in den jeweiligen Rollen
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://ftp2.de.debian.org/debian/ {{ ansible_distribution_release }} main"
    - "deb http://ftp2.de.debian.org/debian/ {{ ansible_distribution_release }}-updates main"
    - "deb http://security.debian.org/ {{ ansible_distribution_release }}/updates main"
    - "deb http://ftp2.de.debian.org/debian/ {{ ansible_distribution_release }}-backports main"
  when: ansible_distribution == "Debian"

- name: install common packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - sudo
    - vim
    - gawk
    - wget
    - curl
    - mc
    - htop
    - vnstat
    - tmux
    - pastebinit
    - jnettop
    - iotop
    - tcpdump
    - screen
    - strace
    - socat
    - dnsutils
    - host
    - apt-transport-https
    - tshark
    - dwdiff
#    - molly-guard
    - git
    - iperf
    - iperf3
    - mtr
    - iptables-persistent
    - mosh
    - conntrack
    - bridge-utils

- name: deinstalliere nicht gewollte Packete
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - rpcbind
    - exim*

- name: install backports-kernel
  apt:
    default_release: jessie-backports
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - linux-image-4.6.0-0.bpo.1-amd64
    - linux-headers-4.6.0-0.bpo.1-amd64
    # ggf. linux-image
  when: backports_kernel

- name: Aktiviere IPv4 Forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Aktiviere IPv6 Forwarding
  sysctl: name="net.ipv6.conf.all.forwarding" value=1 sysctl_set=yes state=present reload=yes

- name: create user freifunk
  user: name=freifunk shell=/bin/bash

- name: Clone scripts-ffwp
  git: repo=https://github.com/freifunk-westpfalz/scripts-ffwp.git dest=/home/freifunk/scripts-ffwp
  become: yes
  become_method: su
  become_user: freifunk

- name: Clone config-ffwp
  git: repo=https://github.com/freifunk-westpfalz/config-ffwp.git dest=/home/freifunk/config-ffwp
  become: yes
  become_method: su
  become_user: freifunk

#todo: exclusiv
- name: add sshkeys for root
  authorized_key:
    user: root
    key: "{{ lookup('file', 'keyfiles/' + item + '.pub') }}"
  with_items: "{{ administratorenteam }}"
  when: administratorenteam

- name: add sshkeys for freifunk
  authorized_key:
    user: freifunk
    key: "{{ lookup('file', 'keyfiles/' + item + '.pub') }}"
  with_items: "{{ administratorenteam }}"
  when: administratorenteam

- name: Disable empty password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
  notify: restart sshd

- name: Disable remote root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"
  notify: restart sshd

- name: Disable password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  notify: restart sshd

- locale_gen: name=de_DE.UTF-8 state=present
