---

- name: Fire all previous handlers
  meta: flush_handlers

- name: Schl端ssel f端r Bird hinzuf端gen
  #wget -O - http://bird.network.cz/debian/apt.key | gpg --with-key-data
  apt_key: id=AC0E47584A7A714D url=http://bird.network.cz/debian/apt.key state=present

- name: Bird-Repo hinzuf端gen
  apt_repository:
        #Bei Problemen ggf. auf jessie aendern
        repo: "deb http://bird.network.cz/debian/ {{ ansible_distribution_release }} main"
        state: present

- name: Bird installieren
  apt:
        pkg: "{{item}}"
        update_cache: yes
        state: installed
  with_items:
        - bird
